import Foundation

/// A data provider backed by real user behavior tracked via ActivityTracker.
/// Conforms to ZeenDataProviding so it's a drop-in replacement for MockDataProvider.
@MainActor
struct LiveDataProvider: ZeenDataProviding {

    private let tracker: ActivityTracker

    init(tracker: ActivityTracker = .shared) {
        self.tracker = tracker
    }

    func todayInput() -> DriftInput {
        tracker.todayDriftInput()
    }

    func timelineForToday() -> [TimelinePoint] {
        tracker.hourlyTimeline()
    }

    func weeklySummary() -> WeeklySummary {
        tracker.weeklySummary()
    }

    // MARK: - Historical Data (for Calendar)

    func historicalRecords(days: Int) -> [DailyRecord] {
        tracker.historicalRecords(days: days)
    }

    // MARK: - Export Report

    static func exportReport(daily: DailySummary, weekly: WeeklySummary, profile: String?) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium

        let dayNames = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

        var lines: [String] = []
        lines.append("╔══════════════════════════════════╗")
        lines.append("║       ZEEN WEEKLY REPORT         ║")
        lines.append("╚══════════════════════════════════╝")
        lines.append("")

        if let name = profile {
            lines.append("👤 \(name)")
        }
        lines.append("📅 Week of \(dateFormatter.string(from: weekly.weekStart))")
        lines.append("")
        lines.append("─── Today ───────────────────────────")
        lines.append("\(daily.score.level.emoji) Drift Score: \(daily.score.value)/100 (\(daily.score.level.label))")
        lines.append("🕐 Calm Hours: \(daily.calmHourCount)")
        lines.append("")

        lines.append("─── This Week ──────────────────────")
        lines.append("📊 Average: \(weekly.averageScore)")
        lines.append("🧘 Deep Focus: \(weekly.totalDeepFocusMinutes) min")
        lines.append("")
        lines.append("   Day   Score   Focus")

        for point in weekly.points {
            let name = dayNames[point.dayIndex % 7]
            let bar = String(repeating: "█", count: point.score / 10)
            lines.append("   \(name)   \(String(format: "%3d", point.score))    \(point.deepFocusMinutes)m  \(bar)")
        }

        lines.append("")
        lines.append("─── Factors ─────────────────────────")
        for factor in daily.score.factors {
            lines.append("  \(factor.title): +\(factor.contribution) (observed: \(factor.observed))")
        }

        lines.append("")
        lines.append("Generated by Zeen · zeen.app")

        return lines.joined(separator: "\n")
    }
}
