import Foundation

protocol ZeenDataProviding {
    func todayInput() -> DriftInput
    func timelineForToday() -> [TimelinePoint]
    func weeklySummary() -> WeeklySummary
}

struct MockDataProvider: ZeenDataProviding {
    func todayInput() -> DriftInput {
        DriftInput(appSwitches: 27, shortSessions: 16, notificationInterruptions: 21, focusBreaks: 8)
    }

    func timelineForToday() -> [TimelinePoint] {
        [
            .init(hour: 7,  score: 12, interruptionCount: 1),
            .init(hour: 8,  score: 18, interruptionCount: 2),
            .init(hour: 9,  score: 22, interruptionCount: 3),
            .init(hour: 10, score: 28, interruptionCount: 4),
            .init(hour: 11, score: 34, interruptionCount: 5),
            .init(hour: 12, score: 52, interruptionCount: 9),
            .init(hour: 13, score: 61, interruptionCount: 10),
            .init(hour: 14, score: 58, interruptionCount: 7),
            .init(hour: 15, score: 47, interruptionCount: 6),
            .init(hour: 16, score: 43, interruptionCount: 4),
            .init(hour: 17, score: 39, interruptionCount: 3),
            .init(hour: 18, score: 36, interruptionCount: 4),
            .init(hour: 19, score: 31, interruptionCount: 2),
            .init(hour: 20, score: 20, interruptionCount: 1),
            .init(hour: 21, score: 14, interruptionCount: 0)
        ]
    }

    func weeklySummary() -> WeeklySummary {
        let weekStart = Calendar.current.date(byAdding: .day, value: -6, to: .now) ?? .now
        return WeeklySummary(
            weekStart: weekStart,
            points: [
                .init(dayIndex: 0, score: 41, deepFocusMinutes: 122),
                .init(dayIndex: 1, score: 54, deepFocusMinutes: 95),
                .init(dayIndex: 2, score: 48, deepFocusMinutes: 113),
                .init(dayIndex: 3, score: 66, deepFocusMinutes: 76),
                .init(dayIndex: 4, score: 58, deepFocusMinutes: 88),
                .init(dayIndex: 5, score: 35, deepFocusMinutes: 154),
                .init(dayIndex: 6, score: 29, deepFocusMinutes: 170)
            ]
        )
    }

    // MARK: - Historical Data for Calendar

    static func historicalRecords(days: Int) -> [DailyRecord] {
        let calendar = Calendar.current
        let today = calendar.startOfDay(for: .now)

        // Seeded "random" scores that are deterministic so the UI is stable
        let scores = [
            24, 38, 52, 19, 45, 67, 31, 28, 72, 43,
            55, 22, 36, 60, 48, 15, 82, 41, 33, 50,
            27, 63, 44, 20, 56, 39, 71, 25, 47, 34
        ]

        return (0..<days).compactMap { offset in
            guard let date = calendar.date(byAdding: .day, value: -(days - 1 - offset), to: today) else { return nil }
            let score = scores[offset % scores.count]
            return DailyRecord(date: date, score: score)
        }
    }

    // MARK: - Export Report

    static func exportReport(daily: DailySummary, weekly: WeeklySummary, profile: String?) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium

        let dayNames = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

        var lines: [String] = []
        lines.append("╔══════════════════════════════════╗")
        lines.append("║       ZEEN WEEKLY REPORT         ║")
        lines.append("╚══════════════════════════════════╝")
        lines.append("")

        if let name = profile {
            lines.append("👤 \(name)")
        }
        lines.append("📅 Week of \(dateFormatter.string(from: weekly.weekStart))")
        lines.append("")
        lines.append("─── Today ───────────────────────────")
        lines.append("\(daily.score.level.emoji) Drift Score: \(daily.score.value)/100 (\(daily.score.level.label))")
        lines.append("🕐 Calm Hours: \(daily.calmHourCount)")
        lines.append("")

        lines.append("─── This Week ──────────────────────")
        lines.append("📊 Average: \(weekly.averageScore)")
        lines.append("🧘 Deep Focus: \(weekly.totalDeepFocusMinutes) min")
        lines.append("")
        lines.append("   Day   Score   Focus")

        for point in weekly.points {
            let name = dayNames[point.dayIndex % 7]
            let bar = String(repeating: "█", count: point.score / 10)
            lines.append("   \(name)   \(String(format: "%3d", point.score))    \(point.deepFocusMinutes)m  \(bar)")
        }

        lines.append("")
        lines.append("─── Factors ─────────────────────────")
        for factor in daily.score.factors {
            lines.append("  \(factor.title): +\(factor.contribution) (observed: \(factor.observed))")
        }

        lines.append("")
        lines.append("Generated by Zeen · zeen.app")

        return lines.joined(separator: "\n")
    }
}
